import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function load(){const context=vm.createContext({structuredClone,console,setTimeout,clearTimeout,Promise,window:{}});vm.runInContext(fs.readFileSync(new URL('../engine/record-store-engine.js',import.meta.url),'utf8'),context);return context.window.reusableRecordStore}
test('generic records preserve status flags provenance and application data',async()=>{const e=load(),s=e.createStore({id:'demo'});await s.initialize();const r=await s.put({id:'a',status:'draft',flags:['review'],data:{anything:42},provenance:{source:'human',evidence:['note']}});assert.equal(r.status,'draft');assert.deepEqual([...r.flags],['review']);assert.equal(r.data.anything,42);assert.equal(r.provenance.source,'human');assert.deepEqual([...r.provenance.evidence],['note'])});
test('generic record history supports undo without application vocabulary',async()=>{const e=load(),s=e.createStore();await s.initialize();await s.put({id:'a',data:{n:1}});await s.patch('a',{data:{n:2}},{actor:'tester'});assert.equal(s.get('a').data.n,2);await s.undo();assert.equal(s.get('a').data.n,1);assert.ok(s.history().some(h=>h.action==='undo'))});
test('generic record import migrates older schemas and preserves provenance',async()=>{const e=load(),s=e.createStore({schemaVersion:2,migrate:(r,from)=>from===1?{...r,data:{...r.data,migrated:true}}:r});await s.initialize();const payload={type:'reusable-record-store',records:[{id:'old',schemaVersion:1,status:'active',flags:[],data:{x:1},metadata:{},provenance:{source:'legacy'},createdAt:'x',updatedAt:'x',revision:1}]};const out=await s.importData(payload);assert.equal(out.count,1);assert.equal(s.get('old').schemaVersion,2);assert.equal(s.get('old').data.migrated,true);assert.equal(s.get('old').provenance.source,'legacy')});
test('record persistence adapter restores application-neutral state',async()=>{const e=load(),adapter=e.memoryAdapter(),a=e.createStore({id:'persist',adapter});await a.initialize();await a.put({id:'x',data:{ok:true}});const b=e.createStore({id:'persist',adapter});await b.initialize();assert.equal(b.get('x').data.ok,true)});
